eureka:
 client:
  fetch-registry: true
  register-with-eureka: true
  serviceUrl:
   defaultZone: http://localhost:8010/eureka/
 instance:
  hostname: localhost
 
 
movie-config-server:
 value: from git 
